### ISSUE TITLE
Chip Range error

### ISSUE THREAD

**Issue by Skriata** [drsam94/mmbccr#1]
The program will throw and error related to the ChipRange when randomizing battle chip challenge

line 14, in randomizeChips
    (config["ChipRange"], Library.standardChipRange()),
  File "/usr/lib/python3.9/configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'ChipRange'

**Comment by drsam94** [comment]
Do you have any more details about the context, e.g seed and conf file, to help with reproducing? I have successfully run with python3.9:


```
$ /usr/bin/python3.9 --version
Python 3.9.2
$ /usr/bin/python3.9 ./rando.py bcc.gba random_out.gba
Randomizing with seed 1870519285206377617
Randomizing Game.BCC
```

The reported error is a KeyError for `'ChipRange'`, which I would expect if you attempted to run with a conffile which did not include a `[ChipRange]` section; the default conffile in the repo, rando_bcc.conf does have such a section.

**Comment by Skriata** [comment]
fixed it

i didn't use -conf to specify one of the config files
